# Generated by Django 3.1 on 2020-11-28 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('professor_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('it_number', models.CharField(max_length=100)),
                ('date_of_absence', models.DateTimeField(default=django.utils.timezone.now)),
                ('absences_left', models.IntegerField(default=0)),
                ('is_failed', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
