# Generated by Django 3.1 on 2020-12-07 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absence.course'),
        ),
    ]
