# Generated by Django 3.1 on 2020-12-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0003_auto_20201207_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
