# Generated by Django 3.1 on 2020-12-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0006_auto_20201207_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='users',
            new_name='users_available',
        ),
    ]
